name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME : "localseokit"
  EB_APPLICATION_NAME       : "localseokit-bucket"
  EB_ENVIRONMENT_NAME       : "localseokit-env"
  DEPLOY_PACKAGE_NAME       : "localseokit-${{ github.sha }}.zip"
  AWS_REGION                : "us-west-1"

on: 
  push:
    branches:
      main

jobs:
  CI Pipeline:
    runs-on  : ubuntu-latest

    steps:
      - name : Git clone repository
        uses : actions/checkout@v1

      - name : Create ZIP deploment package
        run  : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name : Configure my AWS Credentials
        uses : aws-actions/configure-aws-credentials@v1
        with :
            aws_access-key-id     : ${{ secret.AWS_ACCESS_KEY }}
            aws-secret-access-key : ${{ secret.AWS_ACCESS_KEY }}
            aws-region : ${{ enc.AWS_REGION }}

      - name : Copy Deployment Package to S3 Bucket
        run  : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

      - name : 
        run  : echo "CI Pipeline successfully completed."